// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEOCpdOASApYOaD_RYbBcmWkBqgiXPSU',
    appId: '1:399150623152:web:19caaf5efad8f93e528e75',
    messagingSenderId: '399150623152',
    projectId: 'social-app-3a3b5',
    authDomain: 'social-app-3a3b5.firebaseapp.com',
    storageBucket: 'social-app-3a3b5.appspot.com',
    measurementId: 'G-E1MHDL9D3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpUaIgJY97nGUsywlnJq9zDaw5L3OrVuM',
    appId: '1:399150623152:android:955b934b3d2f0a29528e75',
    messagingSenderId: '399150623152',
    projectId: 'social-app-3a3b5',
    storageBucket: 'social-app-3a3b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6J_4NM17OnlM4VqArdo6z4u7sKE-CyQ',
    appId: '1:399150623152:ios:b51fb7864e5f9fd6528e75',
    messagingSenderId: '399150623152',
    projectId: 'social-app-3a3b5',
    storageBucket: 'social-app-3a3b5.appspot.com',
    androidClientId: '399150623152-ls6lpn2mk27fuutemqp9scnnvuq4dghj.apps.googleusercontent.com',
    iosClientId: '399150623152-c69ikgn3h2ed5dlfed29hda7j17cnq23.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6J_4NM17OnlM4VqArdo6z4u7sKE-CyQ',
    appId: '1:399150623152:ios:b51fb7864e5f9fd6528e75',
    messagingSenderId: '399150623152',
    projectId: 'social-app-3a3b5',
    storageBucket: 'social-app-3a3b5.appspot.com',
    androidClientId: '399150623152-ls6lpn2mk27fuutemqp9scnnvuq4dghj.apps.googleusercontent.com',
    iosClientId: '399150623152-c69ikgn3h2ed5dlfed29hda7j17cnq23.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPEOCpdOASApYOaD_RYbBcmWkBqgiXPSU',
    appId: '1:399150623152:web:fabc9739f3488740528e75',
    messagingSenderId: '399150623152',
    projectId: 'social-app-3a3b5',
    authDomain: 'social-app-3a3b5.firebaseapp.com',
    storageBucket: 'social-app-3a3b5.appspot.com',
    measurementId: 'G-GRTJ310BQH',
  );
}
